#test pipeline to deploy source code to external repository

name: $(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'ubuntu-latest'
  
trigger:
- master

step:
- script: |
    scp -r . bvalasek@ssh-bvalasek.alwaysdata.net:/home/bvalasek/www
    
  displayName: 'deploy to webhost'
