#test pipeline to deploy source code to external repository

name: $(Date:yyyyMMdd)$(Rev:.r)
  
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

- task: scp upload
inputs: |
    password:branECKO20
    script: |
    scp -r . bvalasek@ssh-bvalasek.alwaysdata.net:/home/bvalasek/www
    
  displayName: 'deploy to webhost'
